import Die from "./components/Die";
import React from "react";
import { nanoid } from "nanoid";
import Confetti from "react-confetti";

function App() {
  const [dice, setDice] = React.useState(() => generateAllNewDice());

  // Check if the game is won by verifying if all dice are equal and held.
  const gameWon =
    dice.every((die) => die.isHeld) &&
    dice.every((die) => die.value === dice[0].value);

  const newGameRef = React.useRef(null);

  const [rolls, setRolls] = React.useState(0);

  /**
   * Generates an array of 10 new dice objects.
   * @returns An array of 10 new dice objects, each with a random value between 1 and 6,
   * an isHeld property set to false, and a unique id generated by nanoid.
   */
  function generateAllNewDice() {
    return new Array(10).fill(0).map(() => ({
      value: Math.ceil(Math.random() * 6),
      isHeld: false,
      id: nanoid(),
    }));
  }

  /**
   * Rolls the dice that are not held, updating their values to a new random number between 1 and 6.
   * Increments the roll count by 1 each time the dice are rolled.
   */
  function rollDice() {
    setDice((prevDice) =>
      prevDice.map((dice) =>
        dice.isHeld === false
          ? { ...dice, value: Math.ceil(Math.random() * 6) }
          : dice
      )
    );
    setRolls((prevRolls) => prevRolls + 1);
  }

  /**
   * Toggles the isHeld state of a die with the specified id.
   * @param {*} id - The id of the die to toggle.
   */
  function hold(id) {
    setDice((prevDice) =>
      prevDice.map((dice) =>
        dice.id === id ? { ...dice, isHeld: !dice.isHeld } : dice
      )
    );
  }

  /**
   * Starts a new game by generating a new set of dice and resetting the roll count.
   */
  function newGame() {
    setDice(generateAllNewDice());
    setRolls(0);
  }

  // Map over the dice array to create an array of Die components.
  const diceElements = dice.map((dieObj) => (
    <Die
      key={dieObj.id}
      value={dieObj.value}
      isHeld={dieObj.isHeld}
      hold={hold}
      id={dieObj.id}
    />
  ));

  /**
   * Sets the best score in localStorage if the current rolls are less than the stored best score.
   * @returns The best score from localStorage or the current rolls if no best score exists.
   */
  function setBestScore() {
    const bestScore = localStorage.getItem("bestScore");
    if (!bestScore || rolls < bestScore) {
      localStorage.setItem("bestScore", rolls);
      return rolls;
    } else {
      return bestScore;
    }
  }

  // Focus the "New Game" button when the game is won.
  React.useEffect(() => {
    if (gameWon) {
      newGameRef.current.focus();
    }
  }, [gameWon]);

  return (
    <main>
      {/* Render confetti if the game is won */}
      {gameWon && <Confetti />}
      {/* Screen reader only announcement */}
      <div className="sr-only" aria-live="polite">
        {gameWon && (
          <p>
            Congratulations! You won the game! Click "New Game" to start a new
            game.
          </p>
        )}
      </div>

      <h1 className="title">Tenzies</h1>
      <p className="instructions">
        Click a die to hold the value or release the held value. You win when
        all die have the same value.
      </p>
      {/* Win message and score display */}
      {gameWon && (
        <p className="win-message">
          You won! You rolled a total of {<strong>{rolls}</strong>} times!
          <br />
          Your best score is: {<strong>{setBestScore()}</strong>} rolls.
        </p>
      )}
      {/* Die elements display */}
      <div className="dice-container">{diceElements}</div>

      <button
        className="roll-dice"
        onClick={gameWon ? newGame : rollDice}
        aria-label={gameWon ? "Start New Game" : "Roll Dice"}
        ref={newGameRef}
      >
        {gameWon ? "New Game" : "Roll Dice"}
      </button>

      <footer>
        <small>2025 Jack Day</small>
      </footer>
    </main>
  );
}

export default App;
